#!/usr/bin/env python
import os
import shutil
from waflib import Logs


def build(bld):
    # TODO Remove this redundant installdir calculation
    bundle     = 'lmms.lv2'
    installdir = os.path.join(bld.env.LV2DIR, bundle)

    bld.objects(source='lb303.c', includes='..')

    for f in ['lb303.ttl']:
        bld(features='subst', source=f, target=os.path.join(bundle,f), install_path=installdir)

# vim: ts=8:sts=4:sw=4:et
