#!/usr/bin/env python
import os
import shutil
import re
from waflib import Logs

def build(bld):
    return	
    # FIXME: Actually handle dependencies in src/wscript.
    # We shouldn't need to pull in transients...
    bld.program(source='test_oscillator.c',
            target='test_oscillator',
            includes='. ../src',
            use='oscillator blep M',
            install_path=None)
    
    bld.program(source='test_lfo.c',
            target='test_lfo',
            includes='. ../src',
            use='lfo oscillator blep M',
            install_path=None)

# vim: ts=8:sts=4:sw=4:et
