#!/usr/bin/env python
import os
import shutil
from waflib import Logs

def configure(conf):
    conf.env.append_value('PLUGINS', 'envelope_generator')

def build(bld):
    # TODO Remove this redundant installdir calculation
    bundle     = 'lmms.lv2'
    installdir = os.path.join(bld.env.LV2DIR, bundle)

    bld.stlib(source='envelope_generator.c', includes='..', use='envelope', target='envelope_generator')

    for f in ['envelope_generator.ttl']:
        bld(features='subst', source=f, target=os.path.join(bundle,f), install_path=installdir)

# vim: ts=8:sts=4:sw=4:et
