#!/usr/bin/env python
import os
import shutil
from waflib import Logs


def build(bld):
    # TODO Remove this redundant installdir calculation
    bundle     = 'lmms.lv2'
    installdir = os.path.join(bld.env.LV2DIR, bundle)

    bld.objects(source='triple_oscillator.c', includes='..',
            use=['basic_filters','envelope','oscillator'],
            target='triple_oscillator')

    for f in ['triple_oscillator.ttl']:
        bld(features='subst', source=f, target=os.path.join(bundle,f), install_path=installdir)

# vim: ts=8:sts=4:sw=4:et
