#!/usr/bin/env python
import os
import shutil
from waflib import Logs

def build(bld):
    bundle     = 'lmms.lv2'
    installdir = os.path.join(bld.env.LV2DIR, bundle)

    # Plugin environment
    penv                   = bld.env.derive()
    penv['cshlib_PATTERN'] = bld.env['pluginlib_PATTERN']

    plugins = ['lb303']
    src     = ['lmms_lv2.c']

    for p in plugins:
        bld.recurse(p)

    bld.shlib(source=src, target='%s/lmms' % bundle, use=plugins, install_path=installdir, env=penv)

    for f in ['manifest.ttl']:
        bld(features='subst', source=f, target=os.path.join(bundle,f), install_path=installdir)

# vim: ts=8:sts=4:sw=4:et
